// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aicpnaomarzgborltdkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpY3BuYW9tYXJ6Z2Jvcmx0ZGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Nzg2MTcsImV4cCI6MjA3MzE1NDYxN30.u8UCYFCqADKYj-eWrj_9c0STBX733jBhU2sHA_8WNj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});